ssl_certificate /etc/nginx/ssl/staging.crt;
ssl_certificate_key /etc/nginx/ssl/private/staging.key;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers off;
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 1d;
