server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name auth.lab.example.ac.kr huly.lab.example.ac.kr files.lab.example.ac.kr s3.lab.example.ac.kr hf.lab.example.ac.kr;
    return 301 https://$host$request_uri;
}
