server {
    listen 443 ssl;
    server_name auth.lab.snu.ac.kr;

    include /etc/nginx/snippets/ssl-params.conf;
    include /etc/nginx/snippets/security-headers.conf;

    client_max_body_size 100M;

    location / {
        set $authentik_upstream http://authentik-server:9000;
        include /etc/nginx/snippets/proxy-params.conf;
        include /etc/nginx/snippets/websocket.conf;
        proxy_pass $authentik_upstream;
    }
}
