server {
    listen 443 ssl;
    server_name hub.lab.snu.ac.kr;

    include /etc/nginx/snippets/ssl-params.conf;
    include /etc/nginx/snippets/security-headers.conf;
    include /etc/nginx/snippets/upload-large.conf;

    client_max_body_size 50G;

    location / {
        set $gitea_upstream http://gitea:3000;
        include /etc/nginx/snippets/proxy-params.conf;
        proxy_pass $gitea_upstream;
    }
}
