server {
    listen 443 ssl;
    server_name mlflow.lab.snu.ac.kr;

    include /etc/nginx/snippets/ssl-params.conf;
    include /etc/nginx/snippets/security-headers.conf;
    include /etc/nginx/snippets/upload-large.conf;

    client_max_body_size 50G;

    location /outpost.goauthentik.io {
        set $authentik_outpost http://authentik-outpost-mlflow:9000;
        include /etc/nginx/snippets/proxy-params.conf;
        proxy_pass $authentik_outpost;
    }

    location @goauthentik_proxy_signin {
        internal;
        add_header Set-Cookie $auth_cookie;
        return 302 /outpost.goauthentik.io/start?rd=$scheme://$http_host$request_uri;
    }

    location / {
        auth_request /outpost.goauthentik.io/auth/nginx;
        auth_request_set $auth_cookie $upstream_http_set_cookie;
        error_page 401 = @goauthentik_proxy_signin;

        set $mlflow_upstream http://mlflow:5000;
        include /etc/nginx/snippets/proxy-params.conf;
        proxy_pass $mlflow_upstream;
    }
}
