server {
    listen 443 ssl;
    server_name hf.lab.example.ac.kr;

    include /etc/nginx/snippets/ssl-params.conf;
    include /etc/nginx/snippets/security-headers.conf;
    include /etc/nginx/snippets/upload-large.conf;

    client_max_body_size 1G;

    location / {
        set $hf_ui http://hf-ui:8080;
        include /etc/nginx/snippets/proxy-params.conf;
        include /etc/nginx/snippets/websocket.conf;
        proxy_pass $hf_ui;
    }
}
