server {
    listen 443 ssl;
    server_name data.lab.snu.ac.kr;

    include /etc/nginx/snippets/ssl-params.conf;
    include /etc/nginx/snippets/security-headers.conf;
    include /etc/nginx/snippets/upload-large.conf;

    client_max_body_size 10G;

    location / {
        set $grist_upstream http://grist:8484;
        include /etc/nginx/snippets/proxy-params.conf;
        include /etc/nginx/snippets/websocket.conf;
        proxy_request_buffering off;
        proxy_pass $grist_upstream;
    }
}
