server {
    listen 443 ssl;
    server_name office.lab.snu.ac.kr;

    include /etc/nginx/snippets/ssl-params.conf;

    client_max_body_size 1G;

    location ^~ /browser {
        set $collabora_upstream http://collabora:9980;
        include /etc/nginx/snippets/proxy-params.conf;
        proxy_pass $collabora_upstream;
    }

    location ^~ /hosting/discovery {
        set $collabora_upstream http://collabora:9980;
        include /etc/nginx/snippets/proxy-params.conf;
        proxy_pass $collabora_upstream;
    }

    location ^~ /cool {
        set $collabora_upstream http://collabora:9980;
        include /etc/nginx/snippets/proxy-params.conf;
        include /etc/nginx/snippets/websocket.conf;
        proxy_pass $collabora_upstream;
    }
}
