server {
    listen 443 ssl;
    server_name storage.lab.snu.ac.kr;

    include /etc/nginx/snippets/ssl-params.conf;
    include /etc/nginx/snippets/security-headers.conf;

    client_max_body_size 1G;

    location / {
        set $minio_console http://minio:9001;
        include /etc/nginx/snippets/proxy-params.conf;
        include /etc/nginx/snippets/websocket.conf;
        proxy_pass $minio_console;
    }
}
