name: lab_ops

services:
  minio-mc:
    image: ${MINIO_MC_IMAGE}
    container_name: lab-minio-mc
    profiles: ["tools"]
    entrypoint: ["sleep", "infinity"]
    environment:
      TZ: ${TZ}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - lab_data

networks:
  lab_data:
    external: true
